/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    ContentPipeline: typeof import('./src/components/dashboard/ContentPipeline.vue')['default']
    DailyTasks: typeof import('./src/components/dashboard/DailyTasks.vue')['default']
    DistributionPlan: typeof import('./src/components/dashboard/DistributionPlan.vue')['default']
    GrowthInsights: typeof import('./src/components/dashboard/GrowthInsights.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroCard: typeof import('./src/components/dashboard/HeroCard.vue')['default']
    IdeaInbox: typeof import('./src/components/dashboard/IdeaInbox.vue')['default']
    MaterialIcon: typeof import('./src/components/common/MaterialIcon.vue')['default']
    MobileBottomNav: typeof import('./src/components/layout/MobileBottomNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    TopNavbar: typeof import('./src/components/layout/TopNavbar.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_c35930d98cbaa42cd3c0a603e0439e94/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_c35930d98cbaa42cd3c0a603e0439e94/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
  }
}
